# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "270763c46529709da6afbb8778458560"
name = "promo-banner-app"
handle = "promo-banner-app-4"
application_url = "https://meradukann.vercel.app"
embedded = true


[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
